spring.application.name: disco

server:
  port: 8761

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 5
    client:
      registerWithEureka: false
      fetchRegistry: false
      serviceUrl:
        defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/