server.port: 8761

spring.application.name: disco

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 5
    client:
      registerWithEureka: false
      fetchRegistry: false
      serviceUrl:
        defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/