version: "2"

services:
  slip:
    image: jmonsinjon/slip:latest
    # Do no expose external port (we don't care accessing it from the outside)

  poule:
    image: jmonsinjon/poule:latest
    ports:
      - "8080:8080"