version: "3"

services:
  slip:
    image: jmonsinjon/slip:latest
    # Do no expose external port (we don't care accessing it from the outside)
    deploy:
        replicas: 2
        update_config:
            parallelism: 2
            delay: 5s

  poule:
    image: jmonsinjon/poule:latest
    ports:
      - "8080:8080"